In [1]:
# Advance Numpy!!

In [6]:
import numpy as np

In [9]:
arr = np.ones((3,4))

In [10]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [12]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
np.empty((3,4),int)

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [20]:
np.eye(3) # n*n matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
import pandas as pd

In [23]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [24]:
import random 

In [28]:
random.choice((1,2,3,4,5,6))

3

In [33]:
random.choice("sourabh")

'o'

In [35]:
random.randrange(1,1000)

765

In [47]:
random.random() # gives any random number between 0 and 1 0 is included and 1 is excluded

0.6543232416062877

In [48]:
l = [1,2,3,4,5] 
random.shuffle(l)

In [49]:
l

[2, 5, 3, 1, 4]

In [50]:
random.uniform(7,14) #  a no. between 7 and 14

7.8759202919970095

In [51]:
np.random.rand(2,3)

array([[0.74209706, 0.9020603 , 0.94730013],
       [0.82952098, 0.09115096, 0.91282365]])

In [52]:
np.random.rand(1)

array([0.57527099])

In [53]:
np.random.randn(2,3)

array([[-2.14024407, -0.29838684, -0.12913875],
       [ 0.18674869,  0.43976321, -0.13419153]])

In [55]:
np.random.random_sample()

0.29180584432963097

In [57]:
np.random.randint(1,5, size = (3,4))

array([[2, 1, 1, 2],
       [3, 1, 4, 2],
       [3, 1, 1, 1]])

In [58]:
arr.size

12

In [59]:
arr.shape

(3, 4)

In [60]:
arr.ndim

2

In [61]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [69]:
arr.reshape(12,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
arr.reshape(6,2) # array size cannot change

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
arr.reshape(3, -100)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
arr.reshape(4,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
arr.reshape(3,4).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])