In [1]:
# Advance Numpy2!!

In [2]:
import numpy as np

In [3]:
data = np.array([[1],[2],[3]])

In [4]:
data.ndim

2

In [5]:
data

array([[1],
       [2],
       [3]])

In [6]:
np.squeeze(data)

array([1, 2, 3])

In [7]:
a = np.squeeze(data)

In [8]:
a

array([1, 2, 3])

In [9]:
a.ndim

1

In [10]:
# repeat

In [11]:
data

array([[1],
       [2],
       [3]])

In [13]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [15]:
a = np.array([[1,2],[3,4]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [18]:
np.repeat(a,2,axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [19]:
np.repeat(a,2,axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [24]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
a= np.array([[1,2],[3,4],[5,6]])

In [27]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.roll(a,1,axis = 1)

array([[2, 1],
       [4, 3],
       [6, 5]])

In [30]:
# Binary operation in Numpy!!

In [33]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [34]:
arr1

array([[2, 2, 7, 4],
       [3, 1, 4, 9],
       [8, 4, 5, 7]])

In [35]:
arr2

array([[1, 8, 7, 8],
       [7, 5, 9, 4],
       [8, 2, 6, 8]])

In [36]:
arr1+arr2

array([[ 3, 10, 14, 12],
       [10,  6, 13, 13],
       [16,  6, 11, 15]])

In [37]:
arr1-arr2

array([[ 1, -6,  0, -4],
       [-4, -4, -5,  5],
       [ 0,  2, -1, -1]])

In [38]:
arr1**arr2

array([[       2,      256,   823543,    65536],
       [    2187,        1,   262144,     6561],
       [16777216,       16,    15625,  5764801]])

In [39]:
arr1>arr2

array([[ True, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False]])

In [40]:
~arr1

array([[ -3,  -3,  -8,  -5],
       [ -4,  -2,  -5, -10],
       [ -9,  -5,  -6,  -8]])

In [42]:
#Numpy String function!!

In [43]:
arr = np.array(["sourabh", "yadav"])

In [44]:
arr

array(['sourabh', 'yadav'], dtype='<U7')

In [47]:
np.char.upper(arr)

array(['SOURABH', 'YADAV'], dtype='<U7')

In [48]:
np.char.lower(arr)

array(['sourabh', 'yadav'], dtype='<U7')

In [50]:
np.char.upper(np.array(["Data"]))

array(['DATA'], dtype='<U4')

In [52]:
np.char.capitalize(arr)

array(['Sourabh', 'Yadav'], dtype='<U7')

In [53]:
np.char.title(arr)

array(['Sourabh', 'Yadav'], dtype='<U7')

In [54]:
# Mathematical functions!!

In [55]:
arr1

array([[2, 2, 7, 4],
       [3, 1, 4, 9],
       [8, 4, 5, 7]])

In [56]:
np.sin(arr1)

array([[ 0.90929743,  0.90929743,  0.6569866 , -0.7568025 ],
       [ 0.14112001,  0.84147098, -0.7568025 ,  0.41211849],
       [ 0.98935825, -0.7568025 , -0.95892427,  0.6569866 ]])

In [57]:
np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.75390225, -0.65364362],
       [-0.9899925 ,  0.54030231, -0.65364362, -0.91113026],
       [-0.14550003, -0.65364362,  0.28366219,  0.75390225]])

In [60]:
np.tan(arr1)

array([[-2.18503986, -2.18503986,  0.87144798,  1.15782128],
       [-0.14254654,  1.55740772,  1.15782128, -0.45231566],
       [-6.79971146,  1.15782128, -3.38051501,  0.87144798]])

In [61]:
np.mean(arr1)

4.666666666666667

In [62]:
np.max(arr1)

9

In [63]:
np.std(arr1)

2.4608038433722337

In [64]:
np.var(arr1)

6.055555555555556

In [65]:
np.max(arr1)

9

In [66]:
np.log(arr1)

array([[0.69314718, 0.69314718, 1.94591015, 1.38629436],
       [1.09861229, 0.        , 1.38629436, 2.19722458],
       [2.07944154, 1.38629436, 1.60943791, 1.94591015]])

In [67]:
np.exp(arr1)

array([[7.38905610e+00, 7.38905610e+00, 1.09663316e+03, 5.45981500e+01],
       [2.00855369e+01, 2.71828183e+00, 5.45981500e+01, 8.10308393e+03],
       [2.98095799e+03, 5.45981500e+01, 1.48413159e+02, 1.09663316e+03]])

In [68]:
np.power(arr1,3)

array([[  8,   8, 343,  64],
       [ 27,   1,  64, 729],
       [512,  64, 125, 343]])

In [69]:
arr1 - arr2

array([[ 1, -6,  0, -4],
       [-4, -4, -5,  5],
       [ 0,  2, -1, -1]])

In [70]:
np.subtract(arr1, arr2)

array([[ 1, -6,  0, -4],
       [-4, -4, -5,  5],
       [ 0,  2, -1, -1]])

In [71]:
np.add(arr1,arr2)

array([[ 3, 10, 14, 12],
       [10,  6, 13, 13],
       [16,  6, 11, 15]])

In [72]:
arr1 * arr2

array([[ 2, 16, 49, 32],
       [21,  5, 36, 36],
       [64,  8, 30, 56]])

In [73]:
np.multiply(arr1,arr2)

array([[ 2, 16, 49, 32],
       [21,  5, 36, 36],
       [64,  8, 30, 56]])

In [75]:
np.mod(arr1,arr2)

array([[0, 2, 0, 4],
       [3, 1, 4, 1],
       [0, 0, 5, 7]])

In [76]:
np.power(arr1, arr2)

array([[       2,      256,   823543,    65536],
       [    2187,        1,   262144,     6561],
       [16777216,       16,    15625,  5764801]])

In [77]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 2.64575131, 2.        ],
       [1.73205081, 1.        , 2.        , 3.        ],
       [2.82842712, 2.        , 2.23606798, 2.64575131]])

In [78]:
# sorting searching!!

In [81]:
arr = np.array([3,5,7,8,1,2,10,68,95,100])

In [82]:
arr

array([  3,   5,   7,   8,   1,   2,  10,  68,  95, 100])

In [84]:
np.sort(arr)

array([  1,   2,   3,   5,   7,   8,  10,  68,  95, 100])

In [89]:
np.searchsorted(arr, 44)

7

In [90]:
arr1 = np.array([0,1,2,3,0,4])
np.count_nonzero(arr1)

4

In [91]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [92]:
np.where(arr1>0)

(array([1, 2, 3, 5]),)

In [95]:
np.extract(arr1>0, arr1)

array([1, 2, 3, 4])

In [96]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

In [97]:
# matrix >> 2d array

In [98]:
import numpy.matlib as nm

In [99]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [101]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
# Numpy Linear Algebra!!

In [103]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [114]:
arr1 = np.array([[2,3],[4,5]])
arr2 = np.array([[1,3],[4,5]])

In [115]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [117]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [118]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [119]:
b = np.array([16,-8,0])

In [120]:
b

array([16, -8,  0])

In [121]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [122]:
5*2 - 3*4

-2

In [123]:
np.linalg.det(arr1)

-2.0

In [124]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])