In [1]:
# Numpy

In [2]:
import numpy as np


In [3]:
l=[1,2,3,4,5]

In [4]:
arr = np.array(1)

In [5]:
arr

array(1)

In [8]:
type(np.array(1))

numpy.ndarray

In [9]:
arr.ndim


0

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.ndim

2

In [16]:
l = [1,2,3,4,5]

In [28]:
mat=np.matrix(l) # matrix will by default 2d

In [41]:
#np.matrix([[[1,2],[5,6],[7,8]]])

In [42]:
np.array([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [43]:
# more way to convert into array
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [44]:
# matrix is subcalss of array

In [45]:
np.asanyarray([[[1,2],[5,6],[7,8]]]) # Convert the input to an ndarray, but pass ndarray subclasses through.


array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [46]:
mat

matrix([[1, 2, 3, 4, 5]])

In [47]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [48]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [49]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a=5
np.array(a)

array(5)

In [51]:
# array and asarray have no any diffrence!!

In [58]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [58]:
l = [1,2,3,4,5]
arr = np.array(l)
arr


array([1, 2, 3, 4, 5])

In [70]:
a=arr

In [71]:
a

array([1000,    2,    3,    4,    5])

In [72]:
arr[3]

4

In [69]:
arr[3]

4

In [60]:
a

array([1, 2, 3, 4, 5])

In [61]:
arr[0] = 1000

In [66]:
arr

array([1000,    2,    3,    4,    5])

In [76]:
a

array([1000,    2,    3,    4,    5])

In [79]:
b= a.copy()
b[0] = 2000

In [80]:
b

array([2000,    2,    3,    4,    5])

In [81]:
a

array([1000,    2,    3,    4,    5])

In [82]:
# to create array >> array, asarray, asanyarray, deep copy, shallow copy!!

In [83]:
# There ary multiple ways to generate arrays

In [84]:
np.fromfunction(lambda i,j : i==j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [85]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr.shape

(5,)

In [87]:
arr1.shape

(2, 3)

In [88]:
arr1.size

6

In [89]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [90]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [96]:
for i in range(5):
    print(i)

0
1
2
3
4


In [97]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [99]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [100]:
list(range(5))

[0, 1, 2, 3, 4]

In [109]:
iterable=(i*i for i in range(5))

In [110]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [112]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [113]:
np.fromstring('23,34,67', sep = ',')

array([23., 34., 67.])

In [115]:
# np.fromstring('sourabh, yadav,', sep = ',')